apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "73.6.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      defaultDashboardsEnabled: false  # avoid large annotation dashboard failures; import dashboards via ConfigMaps/sidecar instead
      adminPassword: "changeme"
      service:
        type: ClusterIP
    prometheus:
      prometheusSpec:
        retention: "7d"
