apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-config
data:
  MIX_ENV: dev
  NODE_ENV: development
  URL_SCHEME: http
  URL_HOST: localhost
  URL_PORT: "8000"
  DOCKER_RESTART_POLICY: "no"
  DOCKER_WEB_HEALTHCHECK_TEST: /bin/true
  DOCKER_WEB_PORT_FORWARD: "8000"
  DOCKER_WEB_VOLUME: .:/app
