apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Receiver
metadata:
  name: gitops-receiver
  namespace: flux-system
spec:
  type: generic
  events:
    - commit
    - apply
    - kustomization.available
  resources:
    - kind: Kustomization
      name: dev-cluster
      namespace: flux-system
