apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repo-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-age-key
