apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: flux-system
type: Opaque
stringData:
  address: https://hooks.slack.com/services/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