apiVersion: ENC[AES256_GCM,data:2ks=,iv:/39o+UsIusXefEvoXTeQrdbQfioyokG/EYkMW7EQaPM=,tag:xfWg6fr1jvDeO1l2vPCZ0A==,type:str]
kind: ENC[AES256_GCM,data:zEm0PHNV,iv:VbhPpMNbxyzhXrmGuNeXtcRnvJ7lIuOC/Y5OKLYbmas=,tag:d/ls9h1zwlQNr1lAYnk4wQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BZ7sIJ24bCon8LDwI6ErG+5MSEg=,iv:zmf/ljwUmdnmdTwDdOpdMnkCrwGDRtnuxDXQWtluRIY=,tag:vYHXAPKql9LN/Gs/2VZHHg==,type:str]
    namespace: ENC[AES256_GCM,data:CRhxXWhN+HrhDrM=,iv:hIJcO7v4qAJ7COd/RNLgk5EA13owevIfrkNM8aG6BKU=,tag:MRkdx2SWUUTak1DjslyA+g==,type:str]
type: ENC[AES256_GCM,data:/2ekkngF,iv:Ewdyr+KPdcBzw8ziF6DjwTGG6yJh/YUNwuxx2hEsGzw=,tag:WDUK0nj82IrDo5P0NomK5Q==,type:str]
stringData:
    token: ENC[AES256_GCM,data:WaMnkUbxcqjqyeMYA5sq6reHHPQ3cnUtPW1Erup6JKEYmFnVyGy35yPG6FSqrE7pa1+sDISPJqUXVWRbkh+mVdPLtQYykQ6dUvK3WO/ESK2n,iv:U0JAzkhTBPPwY3OON4q8mPeNqlnfof6PKsMmJB71KsI=,tag:ivkodAvMSsciU6FcV2fxow==,type:str]
sops:
    age:
        - recipient: age14m8nps5ej482mjh235p0c88a42sxdsx89cfpem2yscker5jg5gqsxek6a9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ1A3WFJqQ1IyOVpTakpa
            RUxtUE5VaVpSSzBqZysyVlBDSWhBMXFYVFJVCnY4K3I0dU1JVW5TSHUyczJNU0ZG
            YWNtWS9KZHNlZWVBekNNMzFNM0I3RXcKLS0tIFFNV0krQ3NWbGlmK0xCWEZiSUl2
            WWNIcGpheDdsVDl0MmlvcVVLQWtRMjgKl+5jZ09QxBHmECkoM8ZyKDiG8SWSGiJS
            sMBzodke2dDOOqqbOAwoAXTSBhpkjbJimVibNSefGwVxm4iKmsOX1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T07:52:59Z"
    mac: ENC[AES256_GCM,data:VupkvNA9kdXS1JhQm+Wtbwa2Nu784XFTLdy/Pr1Qp4WQWT555MSK43brqQbKam7o4jgMqBg7fv1pyz4opGRqCFPB5m/suGDgmFtxA4PBSYp1D9eXwvhQy2DggGqWpWDEQxrTM/0/d1qfJ61WHMVE/cuTV+3oQOMFvnEyI+T7MCI=,iv:3VosxFXNPhDim9uO0Amkn4q7ABsFSCrmQ1vNIPWhBqU=,tag:k/B2I/8cy9v8dN5+DqAWjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
