apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: flux-system
type: Opaque
stringData:
  token: https://hooks.slack.com/services/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